### ISSUE TITLE
Bug on image showing

### ISSUE THREAD

**Issue by somal** [artyomtugaryov/openvino_workshop#15]
![image](https://user-images.githubusercontent.com/5236713/81170382-41868e80-8fa3-11ea-9ed2-a4f3cebbc97f.png)

**Comment by artyomtugaryov** [comment]
Are you sure you run all previously cells successfully?

**Comment by somal** [comment]
Yes

**Comment by artyomtugaryov** [comment]
Fixed in pull request: https://github.com/artyomtugaryov/openvino_workshop/pull/16
